[project]
name = "GalacticStochastic"
version = "0.0.1"
description = "Tool for getting galactic stochastic background for a given galaxy"
readme = "README.md"
authors = [
  { name="Matthew C. Digman", email="matthew.digman@vanderbilt.edu" }
]
license = { file = "LICENSE" }
dependencies = [
    "numpy>2.0.0",
    "scipy",
    "numba",
    "pytest",
    "h5py"
]
requires-python = ">=3.12"


[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["GalacticStochastic*", "LisaWaveformTools*", "WaveletWaveforms*"]

[project.scripts]
run_gb_ = "GalacticStochastic.cli.run_gb_iterative:main"
